version: "3"

services:
  db:
    container_name: "rinha-db"
    image: postgres
    restart: always
    environment:
      - "POSTGRES_USER=docker"
      - "POSTGRES_PASSWORD=docker"
      - "POSTGRES_DB=docker"
    ports:
      - "5432:5432"
    networks:
      - default

  broker:
    container_name: "rinha-broker"
    image: rabbitmq:management
    environment:
      - "RABBITMQ_DEFAULT_USER=admin"
      - "RABBITMQ_DEFAULT_PASS=admin@123"
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - default

networks:
  default:
    driver: bridge
