<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <RootNamespace>PaymentBroker</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="DotEnv.Core" Version="3.1.0" />
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="8.0.10" />
    <PackageReference Include="NLog" Version="6.0.3" />
    <PackageReference Include="NLog.Config" Version="4.7.15" />
    <PackageReference Include="NLog.Extensions.Logging" Version="6.0.3" />
    <PackageReference Include="Npgsql" Version="8.0.6" />
    <PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" Version="8.0.11" />
    <PackageReference Include="Swashbuckle.AspNetCore" Version="6.6.2" />
  </ItemGroup>

</Project>
